import React from 'react'

import Head from 'next/head'

import Mobile from '../lib/mobile'
import Standard from '../lib/standard'

import fetchAlbumShelf from '../lib/albumdata'
import useMobile from '../lib/useMobile'

// REF --- https://developer.spotify.com/documentation/web-api/reference/#category-albums

export default function App({albums,error}) {

  const [state,setState] = React.useState({
    sorting: 'Release Date', increasing: false, filter: '',
  })

  function setFilter(obj){
    if(obj.sorting){
      if(obj.sorting!==state.sorting)
        setState({...state, sorting: obj.sorting })
      else
        setState({...state, increasing: !state.increasing })
    }
    // setState({...state, sorting:  })
  }


  const isMobile = useMobile();

  return (
    <>
      <Head>
        <title>My Album Shelf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"  />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&display=swap" rel="stylesheet" />
      </Head>

      { isMobile && <Mobile   error={error} state={state} setFilter={setFilter} data={albums} /> }
      {!isMobile && <Standard error={error} state={state} setFilter={setFilter} data={albums} /> }

      <footer>Built with spotify API</footer>
    </>
  )
}


// export async function getServerSideProps(context){
//   return {  props: { albums: await fetchAlbumShelf() }  }
// }

export async function getStaticProps(context){
  return {  props: { albums: await fetchAlbumShelf() }  }
}

