import React from 'react'
import Head from 'next/head'

import fetchAlbumShelf from '../lib/albumdata'
import Header from '../lib/header'
import Albums from '../lib/albums'
import standard from '../styles/Standard.module.css'

// REF --- https://developer.spotify.com/documentation/web-api/reference/#category-albums

export default function App({albums,error}) {

  const [state,setState] = React.useState({
    sorting: 'Release Date', increasing: false, filter: '',
  })

  function setFilter(obj){
    if(obj.sorting){
      if(obj.sorting!==state.sorting)
        setState({...state, sorting: obj.sorting })
      else
        setState({...state, increasing: !state.increasing })
    }
  }

  return (
    <>
      <Head>
      <title>My Album Shelf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"  />
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" /> */}
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&display=swap" rel="stylesheet" />
      </Head>
      
      <div className='title' >My digital album shelf</div>
      <div className='container'>
          <Header state={state} setFilter={setFilter} />
          <main className='main' >
            <Albums state={state} data={albums} />
          </main>

        </div> 
      
      <footer>Built with spotify API</footer>
    </>
  )
}

export async function getStaticProps(context){
  return {  props: { albums: await fetchAlbumShelf() }  }
}

// <Standard error={error} state={state} setFilter={setFilter} data={albums} /> 


// export async function getServerSideProps(context){
  // return {  props: { albums: await fetchAlbumShelf() }  }
// }
